#Hugo configuration
title = "ricky"
baseURL = "https:\/\/ricky.some.com"
languageCode = "en-us"
theme = "tvpage"
disablePathToLower = "true"
enableRobotsTXT = true

[params]
loginId = "1758904"
subfolder = ""
cookiedomain = "some.com"
